// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import { Autocomplete } from 'stimulus-autocomplete'
application.register('autocomplete', Autocomplete)

import Sortable from '@stimulus-components/sortable'
application.register('sortable', Sortable)

import PersonDetailsController from "./person_details_controller"
application.register("person-details", PersonDetailsController)
