services:
  application:
    build: .
    env_file: .env
    environment:
      DATABASE_HOST: database
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/db-data:/var/lib/postgresql/data